"""Pydantic schemas — the source of truth for all agent I/O."""

from aieic_shared.schemas.core import (
    LabPhase,
    StudentStatus,
    Severity,
    StudentRef,
    LabRef,
    SessionRef,
    HealthResponse,
    ErrorDetail,
    ErrorResponse,
)
from aieic_shared.schemas.companion import (
    ChatMessage,
    ChatSource,
    ChatRequest,
    ChatResponse,
    EscalateRequest,
)
from aieic_shared.schemas.participant import (
    LogInteractionRequest,
    LogInteractionResponse,
    StudentContextResponse,
    QuestionType,
)
from aieic_shared.schemas.curriculum import (
    QuizQuestionType,
    QuizQuestion,
    RubricCriterion,
    Rubric,
    GenerateCurriculumRequest,
    CurriculumMaterial,
    ApprovalRequest,
    RequestChangesRequest,
    TypoIssue,
    TypoCheckResponse,
)
from aieic_shared.schemas.assessment import (
    SubmissionType,
    TestCase,
    TestCaseResult,
    CodeGradeResult,
    ReportCriterion,
    ReportEvaluation,
    AnomalyFlag,
    AnomalyReport,
    FeedbackReport,
    ManualReviewRequest,
    AssessmentRequest,
    AssessmentResult,
)
from aieic_shared.schemas.orchestrator import (
    StudentMessageRequest,
    StudentMessageResponse,
    StudentSubmitRequest,
    DashboardLabInfo,
    DashboardMaterialBlock,
    DashboardActivityBlock,
    DashboardActivityCard,
    DashboardGradesBlock,
    DashboardGradesRow,
    DashboardStatsBlock,
    DashboardResponse,
    InstructorApprovalRequest,
)

__all__ = [
    # Core
    "LabPhase",
    "StudentStatus",
    "Severity",
    "StudentRef",
    "LabRef",
    "SessionRef",
    "HealthResponse",
    "ErrorDetail",
    "ErrorResponse",
    # Companion
    "ChatMessage",
    "ChatSource",
    "ChatRequest",
    "ChatResponse",
    "EscalateRequest",
    # Participant
    "LogInteractionRequest",
    "LogInteractionResponse",
    "StudentContextResponse",
    "QuestionType",
    # Curriculum
    "QuizQuestionType",
    "QuizQuestion",
    "RubricCriterion",
    "Rubric",
    "GenerateCurriculumRequest",
    "CurriculumMaterial",
    "ApprovalRequest",
    "RequestChangesRequest",
    "TypoIssue",
    "TypoCheckResponse",
    # Assessment
    "SubmissionType",
    "TestCase",
    "TestCaseResult",
    "CodeGradeResult",
    "ReportCriterion",
    "ReportEvaluation",
    "AnomalyFlag",
    "AnomalyReport",
    "FeedbackReport",
    "ManualReviewRequest",
    "AssessmentRequest",
    "AssessmentResult",
    # Orchestrator
    "StudentMessageRequest",
    "StudentMessageResponse",
    "StudentSubmitRequest",
    "DashboardLabInfo",
    "DashboardMaterialBlock",
    "DashboardActivityBlock",
    "DashboardActivityCard",
    "DashboardGradesBlock",
    "DashboardGradesRow",
    "DashboardStatsBlock",
    "DashboardResponse",
    "InstructorApprovalRequest",
]
