"""
Integrity Agent schemas.

Mirrors the models in Parastou-tech/integrity_agent. Field names and enum values
match the real agent exactly so the Orchestrator can deserialize responses without
any mapping layer.

Owner: Parastou (integrity agent) / Yayun (orchestrator integration)
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class QuestionClassification(str, Enum):
    """How the Integrity Agent classifies a student question."""
    CONCEPTUAL = "CONCEPTUAL"
    PROCEDURAL = "PROCEDURAL"
    CLARIFICATION = "CLARIFICATION"
    DIRECT_SOLUTION = "DIRECT_SOLUTION"
    ANSWER_FARMING = "ANSWER_FARMING"


class ViolationType(str, Enum):
    DIRECT_SOLUTION_REQUEST = "DIRECT_SOLUTION_REQUEST"
    ANSWER_FARMING = "ANSWER_FARMING"
    FREQ_LIMIT_EXCEEDED = "FREQ_LIMIT_EXCEEDED"


class FinalStatus(str, Enum):
    CLEAN = "CLEAN"
    WARNING = "WARNING"
    ESCALATED = "ESCALATED"


class ReportType(str, Enum):
    SESSION = "SESSION"
    POST_LAB = "POST_LAB"


# ============================================================================
# POST /session/start
# ============================================================================

class StartSessionRequest(BaseModel):
    """Body for POST /session/start."""
    student_id: str = Field(..., description="Cal Poly username")
    session_id: str = Field(..., description="UUID generated by Orchestrator")
    lab_id: str = Field(..., description="e.g. 'lab4'")
    course_id: str = Field(default="CSC580")


class StartSessionResponse(BaseModel):
    session_id: str
    started_at: datetime
    message: str = "Session initialized."


# ============================================================================
# POST /session/end
# ============================================================================

class EndSessionRequest(BaseModel):
    student_id: str
    session_id: str


class EndSessionResponse(BaseModel):
    session_id: str
    report_id: str
    ended_at: datetime
    summary: dict


# ============================================================================
# POST /validate  (main policy gate — called before Lab Companion)
# ============================================================================

class ValidateQuestionRequest(BaseModel):
    """Body for POST /validate."""
    student_id: str = Field(..., description="Cal Poly username")
    session_id: str = Field(..., description="Session UUID")
    lab_id: str = Field(..., description="Lab assignment identifier")
    course_id: str = Field(default="CSC580")
    question_text: str = Field(..., min_length=1, max_length=4000)
    conversation_history: list[dict] = Field(
        default_factory=list,
        description="Recent turns: [{'role': 'user'|'assistant', 'content': str}]",
    )


class ValidateQuestionResponse(BaseModel):
    """
    Response from POST /validate.

    Orchestrator decision rules:
    - session_escalated: True  → skip Lab Companion, return refusal to student
    - violation_detected: True → pass classification to Lab Companion as a constraint
    - otherwise               → normal Lab Companion response
    """
    classification: QuestionClassification
    violation_detected: bool = False
    violation_type: Optional[ViolationType] = None
    violation_count: int = 0
    question_count: int = 0
    session_escalated: bool = False


# ============================================================================
# GET /analytics/lab/{lab_id}
# ============================================================================

class StudentLabSummary(BaseModel):
    student_id: str
    question_count: int
    violation_count: int
    status: str  # "ON_TRACK" | "FLAGGED" | "NEEDS_HELP"
    classification_breakdown: dict[str, int]


class LabAnalyticsResponse(BaseModel):
    """
    Per-lab integrity analytics for the instructor dashboard.

    `per_student` feeds the Student Activity tab (integrity status per student).
    `question_stats` feeds the Statistics tab (class-level violation breakdown).
    """
    lab_id: str
    course_id: Optional[str]
    session_stats: dict                      # total_sessions, active_sessions, closed_sessions
    question_stats: dict                     # total_questions, avg_per_student, violation counts
    classification_distribution: dict[str, int]
    avg_session_duration_minutes: Optional[float] = None
    per_student: list[StudentLabSummary] = Field(default_factory=list)
    concept_struggle_summary: list[dict] = Field(default_factory=list)
